
DROP DATABASE IF EXISTS bank_dw;

CREATE DATABASE bank_dw;

USE bank_dw;


CREATE TABLE dim_time (
    TIME_ID INT AUTO_INCREMENT,
    DATE_ DATE,
    PRIMARY KEY (TIME_ID)
);


CREATE TABLE dim_client (
    CLIENT_ID INT AUTO_INCREMENT,
    CLIENT_NAME VARCHAR(255) NOT NULL,
    CLIENT_DATE_BIRTH DATE NOT NULL,
    CLIENT_CONTACT INT, 
    DISTRICT_NAME VARCHAR(255) NOT NULL,
    MUNICIPALITY_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (CLIENT_ID)
)AUTO_INCREMENT = 3;



CREATE TABLE dim_smart_contract (
    CONTRACT_ID INT AUTO_INCREMENT,
    CONTRACT_TYPE VARCHAR(255) NOT NULL,
    CONTRACT_OWNER VARCHAR(255) NOT NULL,
    CONTRACT_CREATION_DATE DATE NOT NULL,
    CONTRACT_EXPIRE_DATE DATE NOT NULL,
    CONTRACT_STATUS VARCHAR(255),
    PRIMARY KEY (CONTRACT_ID)
);


CREATE TABLE fact_bank (
    TIME_ID INT NOT NULL,
    CLIENT_SENDER_ID INT NOT NULL,
    CLIENT_RECEIVER_ID INT NOT NULL,
    CONTRACT_ID INT NOT NULL,
    AMOUNT DECIMAL(12, 2) NOT NULL,
    TIME_STAMP VARCHAR(255) NOT NULL,
    FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (CLIENT_SENDER_ID) REFERENCES dim_client (CLIENT_ID),
    FOREIGN KEY (CLIENT_RECEIVER_ID) REFERENCES dim_client (CLIENT_ID),
    FOREIGN KEY (CONTRACT_ID) REFERENCES dim_smart_contract (CONTRACT_ID),
    PRIMARY KEY (CLIENT_SENDER_ID,CLIENT_RECEIVER_ID,CONTRACT_ID,TIME_STAMP)
);


INSERT INTO dim_client (CLIENT_NAME, CLIENT_DATE_BIRTH, CLIENT_CONTACT, DISTRICT_NAME, MUNICIPALITY_NAME) VALUES ("OPEN ACCOUNT", "NOT APPLIED", "NOT APPLIED", "NOT APPLIED", "NOT APPLIED");







